// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectTxtFile() {
  return window['go']['main']['App']['SelectTxtFile']();
}
